---
name: Build and Deploy React App to CloudFront
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: epitech-crm-front
      DIST: dist
      REGION: eu-west-3
      DIST_ID: EVDJ52DOKKHNC
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    - name: Install Dependencies
      run: |
        node --version
        yarn

    - name: Add environment variables to .env
      run: |
        printf "VITE_APP_CLIENT_ID=${{secrets.VITE_APP_CLIENT_ID}}\VITE_USER_POOL_ID=${{secrets.VITE_USER_POOL_ID}}\VITE_REDIRECT_SIGN_IN=${{secrets.VITE_REDIRECT_SIGN_IN}}\VITE_REDIRECT_SIGN_OUT=${{secrets.VITE_REDIRECT_SIGN_OUT}}\n" >> .env

    - name: Build Static Website
      run: yarn build

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Create invalidation for CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"
